### ISSUE TITLE
Please sign APKs

### ISSUE THREAD

**Issue by IzzySoft** [gdlow/brick-guard#2]
Could you please sign the APKs you attach to releases? Trying to install the one currently attached leads to an error as the signature is missing. Should you have signed it e.g. v3 only, please also sign for v2 and v1 (i.e. all the way down): v2 has only been introduced with Oreo, so all before need v1. Thanks!

**Comment by gdlow** [comment]
Signed

**Comment by IzzySoft** [comment]
Thanks! But:

```
$ apksigner verify --verbose brickguard_v1.1.1.apk 
DOES NOT VERIFY
ERROR: Missing META-INF/MANIFEST.MF
```

Looks like at least v1 signatures are still missing. With minSdk=21, v1 sigs are needed (as described above).
